### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by webdev03** [ILOVETOMAKESTUFF/ilovetomakestuff.github.io#1]
Lowercase the repo name (gh pages docs)
Don't use svelte for now and upload `index.html` with plain HTML

**Comment by ILOVETOMAKESTUFF** [comment]
Okay, I will change the title.

**Comment by webdev03** [comment]
https://ilovetomakestuff.github.io/ is now ready!!

**Comment by ILOVETOMAKESTUFF** [comment]
Wow! Thanks! I also was making a website, but my school blocked it :(

**Comment by ILOVETOMAKESTUFF** [comment]
Also, could I put CSS in the same repo file as the HTML, or do I have to make a new file? If I have to make a new file, then I would be lost in confusion.

**Comment by webdev03** [comment]
You can put it in the same file.

**Comment by ILOVETOMAKESTUFF** [comment]
Thanks

**Comment by Quantum-Codes** [comment]
You can close this issue as you are done with this
